### PR TITLE
Vendor dependencies

### PR DESCRIPTION
**Pull request by mistydemeo**
This is one of two branches I'm submitting as proposals for vendoring Siegfried's dependencies in the Go 1.5+-supported way, which will simplify the process of building packages.

This PR vendors dependencies by actually vendoring the entire source trees of all of the dependencies. #72 uses git submodules instead.

Advantages:

* All required sources will be available in the default checkout.
* Github's generated tarballs will contain all of the contents needed to build Siegfried.

Disadvantages:

* Vendoring all of this content makes the git repository larger, and will require periodic large commits checking in dependency changes.

### CODE REVIEW

**Comment by mistydemeo** [comment]
I've tested, and I'm able to build Siegfried using both branches just fine without running any `go get` steps.

**Comment by richardlehane** [comment]
Thanks very much Misty! I prefer this way - & perhaps using https://github.com/Masterminds/glide in future to automate updating.

**Comment by mistydemeo** [comment]
Great, thanks! This'll make packaging 1.5 much easier.

**Comment by mistydemeo** [comment]
By the way, do you have a sense of when 1.5's coming out?

**Comment by richardlehane** [comment]
hope to get 1.4.5 released this weekend. This will include vendoring plus a few bug fixes.

1.5 is still a little way off - but hopefully in the next month or so

**Comment by richardlehane** [comment]
I've merged develop back into master and tagged a 1.4.5 release. Will do the windows binaries tomorrow and update the website. Great if you could do the deb and brew for this one? (no rush)
Thanks :)

**Pull request merged**
